### ISSUE TITLE
it doesnt work at GKE Autopilot cluster

### ISSUE THREAD

**Issue by farcop** [boredabdel/gke-private-registries#1]
kubectl apply -f cert-ds.yml

`Warning: Autopilot set default resource requests for DaemonSet default/cert-daemonset, as resource requests were not specified. See http://g.co/gke/autopilot-defaults.
Error from server ([denied by autogke-disallow-hostnamespaces] enabling hostPID is not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-disallow-hostnamespaces] enabling hostNetwork is not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-disallow-hostnamespaces] enabling hostPID is not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-disallow-hostnamespaces] enabling hostNetwork is not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-default-linux-capabilities] linux capability <{"NET_ADMIN"}> on container <init> not allowed; Autopilot only allows the capabilities: <["SETPCAP", "MKNOD", "AUDIT_WRITE", "CHOWN", "NET_RAW", "DAC_OVERRIDE", "FOWNER", "FSETID", "KILL", "SETGID", "SETUID", "NET_BIND_SERVICE", "SYS_CHROOT", "SETFCAP"]>. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume etc in container init is accessed in write mode; disallowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-disallow-privilege] container <init> is privileged; not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>): error when creating "cert-ds.yml": admission webhook "validation.gatekeeper.sh" denied the request: [denied by autogke-disallow-hostnamespaces] enabling hostPID is not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-disallow-hostnamespaces] enabling hostNetwork is not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-disallow-hostnamespaces] enabling hostPID is not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-disallow-hostnamespaces] enabling hostNetwork is not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-default-linux-capabilities] linux capability <{"NET_ADMIN"}> on container <init> not allowed; Autopilot only allows the capabilities: <["SETPCAP", "MKNOD", "AUDIT_WRITE", "CHOWN", "NET_RAW", "DAC_OVERRIDE", "FOWNER", "FSETID", "KILL", "SETGID", "SETUID", "NET_BIND_SERVICE", "SYS_CHROOT", "SETFCAP"]>. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume etc in container init is accessed in write mode; disallowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>
[denied by autogke-disallow-privilege] container <init> is privileged; not allowed in Autopilot. Requesting user: <user@mycompany.com> and groups: <["system:authenticated"]>`

**Comment by boredabdel** [comment]
Yeah this is expected as autopilot doesn't support running privileged pods with HostNetwork and HostPID

https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#limits

The easiest will be to try to get your Docker registries to serve traffic with a trusted CA. Otherwise maybe deploying a proxy with trusted CA's in front of your registries if you cannot change how the registries themself work.
