### ISSUE TITLE
Issue on GKE 1.22 containerd

### ISSUE THREAD

**Issue by samos123** [boredabdel/gke-private-registries#3]
I forgot to copy the actual error, but I had to use following syntax on GKE 1.22:
```
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."$REGISTRY_FQDN"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."$REGISTRY_FQDN".tls]
```

probably due to newer containerd?

**Comment by boredabdel** [comment]
yes it seems like that syntax have been deprecated https://github.com/containerd/containerd/blob/main/docs/cri/registry.md

I will have to do some testing

**Comment by boredabdel** [comment]
PR merged
